### ISSUE TITLE
Contributors break

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/designsystem#106]
On view ports between 1200-1350px the contributors will break a little
![screen shot 2018-04-20 at 9 08 59 am](https://user-images.githubusercontent.com/1266923/39022825-bb565ac2-447a-11e8-8928-2e35b5d71c4d.png)
seen in the [buttons](https://designsystem.gov.au/components/buttons/) page in firefox `59.0.2`

**Comment by alex-page** [comment]
Thanks @dominikwilkowski i'll get on this now!

**Comment by alex-page** [comment]
@dominikwilkowski I could not replicate this issue:
![firefox-contributors](https://user-images.githubusercontent.com/19199063/39024145-34f5b4a2-4482-11e8-83b8-dd335a94735f.gif)
