### ISSUE TITLE
why is the footer link not using cta-link?

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/designsystem#108]
![screen shot 2018-04-20 at 9 15 02 am](https://user-images.githubusercontent.com/1266923/39022961-59f9e446-447b-11e8-94d5-f9fc09769d2f.png)

**Comment by dominikwilkowski** [comment]
Feature request than? I'd be all for dog-fooding each component though

**Comment by TrebBrennan** [comment]
I considered it, but the CTA-link component ships with a font-size and set icons size -- the design called for something a little smaller which meant I would have been overriding more CSS than writing new CSS.

I don't see this as an issue (right now). In the future we could look into the CTA link using `em` sizing to inherit the parent size but until more people run into this issue or we have another need to look at inheriting font-sizes we could park this.
