### ISSUE TITLE
Request: OpenWithoutAnimation() and CloseWithoutAnimation() public methods on Accordion

### ISSUE THREAD

**Issue by sirleech** [govau/designsystem#128]
Requesting some new methods on AU.Accordion that give me control of the open/close without the animation. Use case is for mobile viewports where accordions might be closed by default to save space. The same accordion is expanded on large viewports where there is more space.

- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

**Comment by alex-page** [comment]
Hey @sirleech thanks so much for the issue can you move it over to the https://github.com/govau/uikit repository 👍
