### ISSUE TITLE
Windows can't build designsystem repository

### ISSUE THREAD

**Issue by alex-page** [govau/designsystem#136]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

As a windows user I would like to build the design system locally so I can contribute to the website.

# What I expected to happen

No issues running the design system in windows.

**Comment by svict4** [comment]
@adamzerella fix was for the `uikit`
Still unable to build this repository (`designsystem`) due to `-p` flag on `mkdir` script commands when running on windows. May want to look at something like https://www.npmjs.com/package/mkdirp

**Comment by alex-page** [comment]
Re opened issue

**Comment by adamzerella** [comment]
@svict4 Now that https://github.com/govau/designsystem/pull/303 has been merged one should be able to successfully build and run the DS on a Windows machine. We've added some more notes to the README.md for future use cases.
