### ISSUE TITLE
Side navigation documentation, guidance and rationale

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#137]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Checklist

- [x] Overview
- [x] Rationale
- [x] Discussion
- [x] Thumbnail icon
- [x] Tags
- [x] Related components
- [x] Code page
- [x] Dependencies
- [x] [Furnace update](https://github.com/govau/furnace/pull/19)
- [x] Contributors (including getting permission for new contributors)
- [x] Accessiblity page
- [x] Live demo page

**Comment by TrebBrennan** [comment]
Completion of the documentation are currently waiting for finalised components.

**Comment by alex-page** [comment]
You can view an example of the documentation page here:
https://designsystem-featureside-nav-test.apps.y.cld.gov.au
