### ISSUE TITLE
Create documentation pages for main navigation component

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#138]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Checklist

- [x] Overview
- [x] Rationale
- [x] Accessiblity
- [x] Code
- [x] Discussion
- [x] Live demo
- [x] Thumbnail icon
- [x] Tags
- [x] Related components
- [x] Dependencies
- [x] Contributors (including getting permission for new contributors)

**Comment by TrebBrennan** [comment]
Completion of the documentation are currently waiting for finalised components.
