### ISSUE TITLE
Review and deploy scroll depth analytics in Google Tag Manager

### ISSUE THREAD

**Issue by gordongrace** [govau/designsystem#141]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

Steps to reproduce:

1. Preview Workspace with 'Scroll Depth' configuration
2. Confirm 'Scroll Depth' tracked in GA (tag and trigger both configured)

GTM Default Workspace ready for review and submission.

**Comment by alex-page** [comment]
Thanks @gordongrace i'll chuck this in for triage

**Comment by pattyde** [comment]
Have had to move this to the upcoming sprint (starting tomorrow) as we weren't able to do it this sprint.

**Comment by alex-page** [comment]
Thanks for the recommendation @gordongrace, after having a look around our analytics today we are happy with the time on page and the click events that we are logging. This gives us plenty of information and I don't think scroll depth would add to much value.

In the future we may look into adding additional features for analytics.
