### ISSUE TITLE
Update Discourse email templates to adhere to Content Guide

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#149]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

The automatic emails sent from Discourse don't adhere to the DTA's [content guide](https://guides.service.gov.au/content-guide/)

# What I expected to happen

Each of the [57 email templates](https://community.digital.gov.au/admin/customize/email_templates) in Discourse should adhere to the content guide.

Some specific examples of things we should look to update:

- Removing `!` from subject lines
- Ensure [hyperlinks](https://guides.service.gov.au/content-guide/content-structure/#hyperlinks) aren't using terms such as "click here" or "read more"
- Make it clear that the community is whole of government, ideally in the subject line
- Use AU spelling (for example, `s` instead of `z`, adding `u` where appropriate)

# Reproducing

- Website URL: https://community.digital.gov.au/admin/customize/email_templates

**Comment by TrebBrennan** [comment]
> RE: Ensure hyperlinks aren't using terms such as "click here" or "read more" 

Some emails have "Click the following link:" so that text-only email clients can still copy-paste the URL. However no emails have link-text like "click here" or "read more"
