### ISSUE TITLE
Button links to community conversations and GitHub in component pages are non-functional

### ISSUE THREAD

**Issue by gordongrace** [govau/designsystem#156]
- [X] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [X] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened
1. Browsed to a component's 'community' sub-page (example: https://designsystem.gov.au/components/accordion/discussion/)
2. Clicked the 'Community' button
3. No redirect to href value (https://community.digital.gov.au/t/accordion)

# What I expected to happen
1. Click button to go to https://community.digital.gov.au/t/accordion (or equivalent thread for a given component)

Note the same problem seems to exist for the 'GitHub' button/link on those sub-pages.

**Comment by alex-page** [comment]
Thanks @gordongrace seems to be a regression!

**Comment by TrebBrennan** [comment]
The links are rendering as buttons, so the href wont work.. I assume that happened with this PR:
https://github.com/govau/uikit/pull/421/commits/2497e9ffa40cedbed639bf914b89c2725bbb9d2c
