### ISSUE TITLE
Header without a link uses <a> should use <div>

### ISSUE THREAD

**Issue by sirleech** [govau/designsystem#175]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

Unexpected hover underline on Header component (when not a link). Not expecting this on the homepage view (larger header) where it is not a link.

# What I expected to happen

No hover decoration

# Reproducing

- Website URL: https://designsystem.gov.au/
- Date: 13 July 2018

Steps to reproduce:

1. Visit Design System
2. Hover over the header

# Attachments

![image](https://user-images.githubusercontent.com/680844/42674569-9f48cf24-86b3-11e8-83a9-9e36fc563bcc.png)

**Comment by alex-page** [comment]
Thanks @sirleech i'll fix this up now!

**Comment by alex-page** [comment]
This will be fixed with this PR:
https://github.com/govau/uikit/pull/443

**Comment by sirleech** [comment]
Champion 🥇

**Comment by pattyde** [comment]
@sirleech just a heads up that this has fixed in master now :)
