### ISSUE TITLE
Make design systems insights board publicly accessible

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#183]
The insights for the design system are currently tracked in a Google Sheets spreadsheet which is only accessible within the DTA.

External members of our community should be able to view these insights without requiring a DTA email account or having to log in to a third party service.

**Comment by pattyde** [comment]
**Blocked** — The G Suite settings for the DTA do not allow sharing Data Studio reports outside of the DTA. Further discussion is needed to determine a suitable alternative.

**Comment by alex-page** [comment]
Going to close this one unfortunately as we can't make our analytics publicly facing despite how awesome it would be.
