### ISSUE TITLE
Documentation of home page

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/designsystem#274]
# Feature Request

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/designsystem/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/designsystem/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

The template for the home page will require documentation.

**Comment by sukhrajghuman** [comment]
draft here: https://gist.github.com/sukhrajghuman/2496a5a570d3bcc07d22edd2fa6f3507

**Comment by alex-page** [comment]
Nice work @sukhrajghuman lets jam on this in the next sprint.

**Comment by alex-page** [comment]
This is good, we should work out what the page looks like and where this content goes.
