### ISSUE TITLE
Documentation basic page

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/designsystem#276]
# Feature Request

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/designsystem/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/designsystem/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

**Comment by sukhrajghuman** [comment]
https://gist.github.com/sukhrajghuman/f3aecc78239f55b46ba04f3990c5ac09

**Comment by alex-page** [comment]
This is good, we should work out what the page looks like and where this content goes now.
