### ISSUE TITLE
Allow users to customise colours in a full page template

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/designsystem#277]
# Feature Request

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/designsystem/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/designsystem/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

As a user I want to see my colours in a full page template

- [x] form for users to input colours in
- [x] API that receives these inputted colours and creates a page
- [x] unit/integration tests for the API
- [x] allow users to add colour blindness filters

**Comment by alex-page** [comment]
Wow we did all these things, nice work @sukhrajghuman and @adamzerella
