### ISSUE TITLE
Need rationale explaining the lobotomised owl approach for spacing

### ISSUE THREAD

**Issue by alex-page** [govau/designsystem#287]
# Bug report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/designsystem/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/designsystem/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Users have noticed that headings do not have a margin top. This is by design and elements should only get a margin top when they follow another element.

https://alistapart.com/article/axiomatic-css-and-lobotomized-owls

## What I expected to happen

This should be documented, either in the `headings` or `body`.

**Comment by sukhrajghuman** [comment]
draft here:

https://gist.github.com/sukhrajghuman/bcf47da3c6640d999a1ec8b851c59395

Should we allow for the spacing to be customisable?

**Comment by alex-page** [comment]
Should be customisable 👍 , we should have a quick example of what the selector looks like. Good work!

Which page do you think this should go on? It is relevant to all components but the code isn't in body. Is it an article in getting started?

**Comment by sukhrajghuman** [comment]
I feel like it could be in an article since we use it in multiple places ( body component, header component )
