### ISSUE TITLE
Template colour changer

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/designsystem#298]
# Feature Request report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/designsystem/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/designsystem/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

*Template colour changer:*
- As a user I want to share the custom colour scheme
- As a user I want to input my colours and see them in the design system
- As a user I want a fast and accessible experience
- As a user I want to change the colours in IE8
- As a user / team member I want to share and talk about the product, a memorable name will be useful

*Tasks*
- [ ] Create a server that either sends back either:
    - [ ] A themed html page with a new css file
    - [ ] A css file to inject into a html page
- [ ] This response should be added to designsystem.gov.au inside an iframe
- [ ] The URL for the iframe should point to the server
- [ ] On submission of form change the url and update the iframe src to load a new page
- [ ] On refresh of the page the iframe src should be based off the page url
- [ ] The URL with eight colours will be very long and have encrypted symbols ( # = %23 ), see if we can shorten it with base64
- [ ] Load different template HTML
- [x] A fun name for the tool ( and fun comments / error messages ) --> **Chameleon**
- [ ] Make it work in IE8 and make it accessible
- [ ] Make sure the colours submitted are actually colours, otherwise there needs to be an error ( server side preferably )
- [ ] Update iframe and URL without refreshing the page
- [ ] Work out an efficient way to get templates and any necessary custom styles ( pulling in HTML from https://govau.github.io/uikit-starter/ and replacing css does not give custom styles )
- [ ] Look into a11y colour checker and how it works, technically we should be able to give all white and it should work out a colour scheme that works for foreground and background (edited)

**Comment by adamzerella** [comment]
I've migrated alot of the relevant issues to https://github.com/govau/chameleon/issues.

Let me know if I've missed some that still need to be done

**Comment by alex-page** [comment]
I am going to close this issue as we have a new repository! wuhuu thanks @adamzerella
