### ISSUE TITLE
Rebuild DS assets to be a more suitable format such as `svg`, `webp` or `jpg xr` etc.

### ISSUE THREAD

**Issue by adamzerella** [govau/designsystem#320]
NOTE: These formats will break in < IE8. svg is probably the only logical option if any: https://caniuse.com/#feat=svg

**Comment by alex-page** [comment]
I think this should be done with the icon library issue @govau/uikit#526

**Comment by alex-page** [comment]
I am going to close this issue, I have updated the #528 ticket with the note about modern file formats. We have to be careful though because IE8 hates SVGs.
