### ISSUE TITLE
Only add customise js on customise page

### ISSUE THREAD

**Issue by alex-page** [govau/designsystem#359]
# Bug report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/designsystem/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/designsystem/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The footer.js should be for code that executes on most pages. A user may never go to the customise page so we shouldn't bundle it with it.

## What I expected to happen

Split the code from the footer.js

**Comment by adamzerella** [comment]
This has been resolved and waiting for QA in `feature/add-templates-landing-page`
