### ISSUE TITLE
Chameleon accessibility is breaking in safari

### ISSUE THREAD

**Issue by alex-page** [govau/designsystem#362]
# Bug report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/designsystem/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/designsystem/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The components can easily change there colorblindness with svg filters in safari. For some reason the full page templates are experiencing issues.

## What I expected to happen

Lets try and fix that ^

**Comment by adamzerella** [comment]
After some investigating with @alex-page we've concluded that Safari is unable to apply SVG filters to iframes with external `src` or external filter files w/ the `srcdoc` attribute.

We've submitted a bug report to Apple 😆 and put together a live demo here: https://github.com/adamzerella/bug-safari-iframe-svgfilter

**Comment by alex-page** [comment]
Solid day of bug hunting :gun:
