### ISSUE TITLE
Create new component contribution guide

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#47]
As someone who wants to contribute something to the design system (code, design artefacts, research) I need to know what's expected of me so I can provide the correct information to the core team.

I need to know what guidelines I'm expected to follow, what format my contributions should be in, how long it should take for someone to get back to me.

I'm essentially volunteering my time to make the design system better for everyone, so this needs to be laid out clearly so I can make my contributions with the least amount of hurdles to clear.

**Comment by pattyde** [comment]
Current [draft document](https://docs.google.com/document/d/1j78qHaILzdflfvz4CydnNSVrV59EURRh6JLxQlhd0is/edit?usp=sharing)

**Comment by TrebBrennan** [comment]
https://github.com/govau/uikit/pull/344

**Comment by pattyde** [comment]
My name is Patrick De Young, and I approve this 👍
