### ISSUE TITLE
Create privacy policy for Discourse community

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#49]
As someone participating in discussions on the Discourse community forum, I need to understand what personal information is collected, where it might be stored, and how it might be used. I can then make an informed decision as to whether or not I want to participate in the community discussions.

**Comment by TrebBrennan** [comment]
Note, these are the default privacy policies which comes with a Discourse.

https://community.service.gov.au/privacy
https://www.discoursehosting.com/privacy-policy/

**Comment by TrebBrennan** [comment]
Solution:
Redirecting the [community privacy page](https://community.service.gov.au/privacy) to [discoursehosting's privacy page](https://www.discoursehosting.com/privacy-policy/) the same way that [govcms community do](https://community.govcms.gov.au/privacy)

Also added a security reminder to the automated welcome direct-message.
