### ISSUE TITLE
Show browser support information on the documentation site

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#60]
As a user on the documentation site looking to use a component from the UI-Kit, I want to know that browsers you've tested these components on so that I can have confidence that it works, and know what bugs not to report.

We have a checklist on the UI-Kit [README.md](https://github.com/govau/uikit#browser-support), maybe we can just link to this as a start.

**Comment by alex-page** [comment]
This is definitely something we need to do. I would love to see a refactor of the get started section and add this information there.

**Comment by pattyde** [comment]
From our browser and device testing checklist. We could add this to our `README.md` as a start.

Name | Version | Platform
--- | --- | ---
Internet Explorer | 8 | Windows 7
Internet Explorer | 9 | Windows 7
Internet Explorer | 10 | Windows 7
Internet Explorer | 11 | Windows 8.1
Edge | Latest | Windows 10
Firefox | Latest | macOS
Firefox | Latest | Windows 10
Firefox | Latest | Android 6
Chrome | Latest | macOS
Chrome | Latest | Windows 10
Chrome | Latest | Android 4.0
Chrome | Latest | Android 6
Safari | Latest (11) | macOS
Safari | Latest -1 (10) | iOS
Samsung | | G S8
Samsung | | G S7
Samsung | | G S6
Chrome | | Pixel 7.1
STOCK | | Lumia 930 8.1

**Comment by pattyde** [comment]
An example taken from the `README` on GDS' [autocomplete component](https://github.com/alphagov/accessible-autocomplete)

![screen shot 2018-06-01 at 10 49 25 am](https://user-images.githubusercontent.com/13226469/40815400-95251502-6589-11e8-9e09-8db3c095ee89.png)

**Comment by alex-page** [comment]
For this ticket we are going to add the browser and device matrix to the `readme.md` and investigate a way to share how we test our components ( that may be an article on how we test our components ).
