### ISSUE TITLE
Tell me that `.no-js` is required

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#63]
As a user who is prototyping in code. I need to know that `.no-js` is required on the parent object so that the JS will work properly.

Assuming that people don't read all the docs, how might we resolve this?

## Ideas

- Right now we say [ If `.no-js` change to `.js` ]
maybe we could say [ If JS is enabled, add `.js` then remove `.no-js` ]
So that if the `.no-js` class is missing it's not a show stopper... But that would mean people might forget to add the `.no-js` class because things seem to work fine for them, soooo;

- Maybe we throw a console error if `.no-js` is not found but JS is enabled?

**Comment by sirleech** [comment]
Is there an alternate way a component can know if there is no javascript without using the class on the HTML tag? It would be nice if the no-js functionality can be encapsulated in a component.

**Comment by alex-page** [comment]
I'm not a fan of doing it per component as it's a best practice technique used in many websites and CMS. I understand why it would be nice to have it per component but if a developer was making there own component that relied on javascript you would want them to use the same pattern.

More than likely components that use javascript in the future will also use the same pattern. We hope to solve this issue with templates.
