### ISSUE TITLE
Add illustrations to the remaining pages on the documentation site

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#65]
Each of the illustrations below needs to have their colours updated to match the new colour palette. They can then be added to the appropriate page on the documentation site.

- [x] Get started
- [x] Community
- [x] Support

![screen_shot_2017-11-29_at_2 40 00_pm](https://user-images.githubusercontent.com/13226469/38346957-a533a9ac-38db-11e8-9c07-0fc1ce94023c.png)

**Comment by Xochi** [comment]
Need access to adobe illustrator to change the colours

**Comment by Xochi** [comment]
Matthew brooks unblocked this by exporting new versions of the illustrations with the updated colour scheme.

**Comment by alex-page** [comment]
Nice one 👍

**Comment by sukhrajghuman** [comment]
closed by #248
