### ISSUE TITLE
How to use the colour system

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#75]
There is a bunch here about why we have foreground colours and background colours for that we know will pass accessibility.

https://medium.com/eightshapes-llc/light-dark-9f8ea42c9081

## Story
"We stress tested our color system with Dropboxes new crazy brand"

## Some ideas from Treb

**Accessibility out of the box was a big priority** so we've created a system where it's easier to understand which colour is design to be paired with another colour.

**Comment by alex-page** [comment]
Brain dump of things I would like explained:

- What variables we recommend changing `$AU-color-background`, `$AU-color-foreground-action`, `$AU-color-foreground-focus`, `$AU-color-foreground-text`
- How do I know my custom colours meet WCAG AA ( what the `a11ycolor` function does )
- How they work together
  - Background and text color is mixed together to make border and muted ( why we do this )
  - Backgrounds generate shades from the original background color
- Foreground on background, why this relationship exists ( An explanation of the grid on the test page )
- Why the focus colour is purple by default
- When colours don’t do all the work we use other methods to convey meaning ( page-alerts )

**Comment by Xochi** [comment]
Currently work in progress:
https://gist.github.com/Xochi/066cc160c2d540198b76fb7881eae238

**Comment by Xochi** [comment]
Currently work in progress:
https://gist.github.com/Xochi/066cc160c2d540198b76fb7881eae238

**Comment by alex-page** [comment]
Thanks @Xochi here is some feedback, really good work overall mate!

1. I really like the intro and it reads really well, we might want to turn this into two articles, this currently reads like version one.
    - A blog post explaining the issues with colour and how the design system hopes to solve them
    - A refined version for developers who need to accomplish a task e.g. change the colours

1. I really like the way the first two paragraphs work together, however the first paragraph talks about accessibility but there isn't really a relationship to colour until the second paragraph, maybe we can flip it and talk about colour and how it relates to accessibility?

1. I think we can probably replace "nascent" with a more plain english word.

1. When I read the text below I really want to know what the solutions are, can we tease them here by adding some small explanation.

> We came up with some interesting solutions for the design system that can help designers bypass the often tedious work to get the right palette.

1. There is a bit of repetition in the second paragraph:
    - Title: `colour palette in seconds`  Para:`colour palette set up in seconds`
    - `overlooked aspect of accessibility is colour` `about getting accessibility right` `accessibility first`, with the intro I felt like I knew it was accessible

1.  I would like a little bit of an explanation somewhere about how to change the variables and apply them throughout the system

1. I'm not convinced about splitting the light and dark theme up is the correct approach. Looking at it logically it makes sense here however I think there might be a better solution 🤔 

1. The links for the components are broken?

**Comment by alex-page** [comment]
Great work @Xochi excited to see this get published!
