### ISSUE TITLE
Why do you use system fonts?

### ISSUE THREAD

**Issue by pattyde** [govau/designsystem#78]
We used to use a webfont (open sans)
and have changed for 2 main reasons,

- **Download speed** People on rural internet shouldn't need to wait for a font to download so that they can interact with government. 
- **Modern OS look good** System fonts are getting much prettier as devices get newer

**Comment by algazel** [comment]
Could consider / look into FontAwesome for iconography: https://fontawesome.com

**Comment by alex-page** [comment]
This is here:
https://designsystem.gov.au/components/core/rationale/#why-system-fonts
