### ISSUE TITLE
Color impairment only works in modern browsers

### ISSUE THREAD

**Issue by TrebBrennan** [govau/designsystem#9]
**Expected**
Demos to show components with non-standard colours.
![screen shot 2018-02-22 at 1 00 04 pm](https://user-images.githubusercontent.com/15899197/36516067-77d20872-17d0-11e8-9f30-97a7cb4157a1.png)

**Result**
Demos show standard colours.
<img width="1089" alt="screen shot 2018-02-22 at 12 59 24 pm" src="https://user-images.githubusercontent.com/15899197/36516076-7e512c1e-17d0-11e8-925d-fc161f79f3be.png">
(Screenshot: Safari 11.0.2, also seen on iOS.11)

**Comment by dominikwilkowski** [comment]
I suggest to add a note rather than building a thing that does this. The gain here is not large enough to warrent us to build a package that parses css and turns each color.

**Comment by alex-page** [comment]
We are trying to show a message however there are some issues with that. The reason this happens in safari is because it supports `css filter` but not `svg filters`. One work around would be checking if we support `svg filters` and hiding and showing the sections.

This currently works in older browsers:
https://github.com/govau/GOLD/blob/master/src/assets/css/a11y/a11y.css#L55

**Comment by dominikwilkowski** [comment]
Yeah we may need to add a note that says webkit safari does not support this feature and sad face emoji

**Comment by alex-page** [comment]
Happy to do that ^ sounds like a quick win in the meantime!

**Comment by alex-page** [comment]
These examples seem to work in safari, I am going to investigate deeper into why these work and ours do not:
https://css-tricks.com/color-filters-can-turn-your-gray-skies-blue/

**Comment by alex-page** [comment]
This is a bug in safari causing this issue:
https://github.com/alex-page/bug-safari-svg

**Comment by dominikwilkowski** [comment]
@alex-page can you make sure you report this upstream: https://github.com/LukyVj/accecss

**Comment by alex-page** [comment]
Yes will do
